### ISSUE TITLE
TRACKING: Whedon automation improvements

### ISSUE THREAD

**Issue by arfon** [openjournals/whedon-api#49]
There's a collection of things that Whedon should be able to do that would help streamline the editorial process even further (this is loosely based on https://joss.readthedocs.io/en/latest/editing.html#after-acceptance):

- [x] Check that DOIs used in the paper resolve https://github.com/openjournals/whedon-api/pull/50
- [x] Check for missing DOIs for references using [Serrano](https://github.com/sckott/serrano) https://github.com/openjournals/whedon-api/pull/50
- [ ] Spell check the paper https://github.com/openjournals/whedon-api/issues/37
- [ ] Verify that the authors of the paper are the same as the Zenodo archive authors
- [ ] Generate CodeMeta JSON-LD files

/ cc @karthik

**Comment by arfon** [comment]
Closing as captured elsewhere now in separate issues.
